dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
    solc:
        optimizer:
            enabled: true
            runs: 200
        remappings:
            - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
    vyper:
        version: null
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}

networks:
    default: kovan
    kovan:
        vrf_coordinator: '0xdD3782915140c8f3b190B5D67eAc6dc5760C46E9'
        link_token: '0xa36085F69e2889c224210F603D836748e7dC0088'
        keyhash: '0x6c3699283bda56ad74f6b855546325b68d482e983852a7a82979cc4807b641f4'
        fee: 100000000000000000
        oracle: '0x2f90A6D021db21e1B2A077c5a37B3C7E75D15b7e'
        jobId: '29fa9aa13bf1468788b7cc4a500a45b8'
        eth_usd_price_feed: '0x9326BFA02ADD2366b30bacB125260Af641031331'
        btc_usd_price_feed: '0x6135b13325bfC4B00278B4abC5e20bbce2D6580e'
        # Change to True if you have an Etherscan API key and want to verify
        verify: False
        update_interval: 60